@echo off
echo Lanzando el Asistente Docente Inteligente (ADI)...
if not exist venv (
    echo Creando entorno virtual...
    python -m venv venv
)
call venv\Scripts\activate
echo Instalando/Actualizando librerias...
pip install -r requirements.txt --quiet
echo Abriendo la aplicacion en el navegador...
streamlit run app/main.py
pause
